### ISSUE TITLE
Jest 28 compatability

### ISSUE THREAD

**Issue by sklawren** [ValentinH/jest-fail-on-console#21]
Please do a major version (semver) update to set devDependencies to Jest 28.

**Comment by ValentinH** [comment]
I'm actually wondering: why do you need this package to update its `devDependencies`? These dependencies should not impact the package users.
`jest-fail-on-console` actually has no dependency nor peer dependency so it should not impact your Jest 28 update.

**Comment by sklawren** [comment]
For some reason, I was getting complaints from npm about dependency clashes but they seemed to have disappeared now that I tried it again.

**Comment by ValentinH** [comment]
I updated Jest on one of my projects yesterday and there was no issue related to this package.
I'll probably update Jest on this package but I will not do a major version update as dev dependencies should not impact it.

**Comment by ValentinH** [comment]
Closing as we couldn't confirm there was a real issue linked to this package. Please comment if need to reopen.
