### ISSUE TITLE
Failures all attributed to first test

### ISSUE THREAD

**Issue by mattyb** [ValentinH/jest-fail-on-console#24]
I'm seeing that this package successfully fails the test suite, but that all the failures are assigned to the first test regardless of which one caused the error. Is that an expected behavior? I'm on @jest/core 26.6.3

**Comment by ValentinH** [comment]
No this is not the expected behavior. I haven't observed this on my codebases, are you able to share an example repository?

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
