### ISSUE TITLE
Is there a way to not fail a test on console.error, but still print?

### ISSUE THREAD

**Issue by billyvg** [ValentinH/jest-fail-on-console#28]
I would still like to see the `console.error` message when it happens, but be able to have the test *not* fail.

**Comment by ValentinH** [comment]
What you are looking for might be achievable by using the `skipTest` option: https://github.com/ValentinH/jest-fail-on-console#skiptest

**Comment by clemp6r** [comment]
This library could call the original console method, as following:

```
console[methodName] = (...args) => {
  newMethod(...args);
  originalMethod(...args);
}
```

That makes sens to me: the goal of this library is to fail the tests under some conditions, not to alter what is printed is the console.

**Comment by ValentinH** [comment]
I like this idea. We could add this behavior as a new option and make it the default. We would then release a new major version.

**Comment by vernak2539** [comment]
I would love this functionality as well. 

My use case is that I have multiple tests where `console.error` is called, but I cannot control when it gets called as the code being executed is outside of my control.

I'd really like to have the option to:
1. Fail tests if the output of the `console[method]` call matches on certain text
2. Output all other console messages (even errors) and not fail

I can potentially submit a PR if you could point me in the right direction

**Comment by ValentinH** [comment]
I think that @clemp6r proposal is good. We could change the default behavior to let all logs go to the console and only make the test fail.

**Comment by vernak2539** [comment]
@ValentinH I've opened https://github.com/ValentinH/jest-fail-on-console/pull/48 and would appreciate any feedback you have
