### ISSUE TITLE
Potential copyright infringement

### ISSUE THREAD

**Issue by Maxim-Mazurok** [ValentinH/jest-fail-on-console#34]
See https://github.com/thomasbrodusch/vitest-fail-on-console/issues/7

> I'm not a licensing specialist, but in https://github.com/ValentinH/jest-fail-on-console/blob/main/LICENSE it says "...requiring preservation of copyright and license notices..." yet in https://github.com/thomasbrodusch/vitest-fail-on-console/blob/develop/license there's no mention of the original project or Valentin Hervieu

**Comment by ValentinH** [comment]
Thanks for taking the time to create the issue.

To be honest, I was a bit surprised when I saw that this repository existed a few weeks ago. I actually started using Vitest and I almost started looking into creating a Vite flavor of this lib but I noticed that someone already did so. 🤣

Licenses are a boring topic to me so I don't mind of there is an infringement at all or not. The Vitest version maintainer will probably do a better job at maintaining it that I would do as I'm not using Vitest on a real project at the moment.

**Comment by thomasbrodusch** [comment]
Hi @ValentinH 

There is no copyright infringement in `vitest-fail-on-console` as your project was well credited ;)
Plus, there are some differences between those two projects.

I've explained the whole thing to @Maxim-Mazurok here : 
> https://github.com/thomasbrodusch/vitest-fail-on-console/issues/7#issuecomment-1465738135

Please feel free to contact me if you have further interrogations about it!

**Comment by ValentinH** [comment]
There is really no issue in my side @thomasbrodusch , no worries. 🙂

One question, do you plan to backport new contributions from this repo to the Vite one or you rather see them fully separated?

**Comment by thomasbrodusch** [comment]
@ValentinH Glad to know that ! 
I really appreciate your work on `jest-fail-on-console` and I didn't want any bad situation between us 🙂

I think it will be a good thing to **backport new contributions from `jest-fail-on-console` to `vitest-fail-on-console`**
You can totally make some pull-request directly on the repo or ping me when there is a **major release** so I can include them.

What do you think about it?

**Comment by ValentinH** [comment]
Yes this is fine to me. For example, I merge over PR this week that add supports for groups.
