### ISSUE TITLE
Support for `groupCollapsed`/`groupEnd`

### ISSUE THREAD

**Issue by lennym** [ValentinH/jest-fail-on-console#36]
Where console calls are wrapped in a `console.groupCollapsed` it would be good to have the group heading included in the message passed to `silenceMessage`.

In our case we use `recoil` which `console.warn`s [arbitrary objects collapsed with a predictable header](https://github.com/facebookexperimental/Recoil/blob/02decc25c133d7ddd8289d9b452821d525ec57bd/packages/shared/util/Recoil_stableStringify.js#L143-L147). We'd like to be able to use this header to ignore the warnings rather than having to remove fail-on-warn completely.

I'd imagine passing any group context as an additional argument to `silenceMessage` would be _reasonably_ straightforward. Happy to put together a PR if required.

**Comment by ValentinH** [comment]
I didn't know this group feature. I'd be happy to review a PR. 😊

**Comment by lennym** [comment]
Thanks. We'll likely put together a PR in the next few days.

Are you broadly happy with the approach to add additional context as a third parameter to `silenceMessage`?

**Comment by ValentinH** [comment]
Yes I'm ok with this.
I hesitated to do a breaking change and switch to a single object argument but I'm not sure it's worth the hassle.
