### ISSUE TITLE
Jest exit code is still 0 when jest fails, causing Jenkins builds to be successful 

### ISSUE THREAD

**Issue by stanislavlevitt** [ValentinH/jest-fail-on-console#42]
If all the assertions within a test pass, Jest will have an exit code of 0 despite a specific test being marked as fail due to a console error.

This in turn cause builds to be successful with failing tests.

Taking a quick look at this repo, I think you are causing the console messages, but not doing anything to jest itself, so the exit code is unchanged,

**Comment by ValentinH** [comment]
This library is just throwing when a console call is detected. It's weird because I'm pretty sure that the tests are failing if just a console method is called.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
