### ISSUE TITLE
Incompatible with `chalk@5`

### ISSUE THREAD

**Issue by kopach** [ValentinH/jest-fail-on-console#43]
I have chalk@5 in my project. When I run tests with `jest-fail-on-console` enabled — I'm getting errors like `TypeError: chalk.red is not a function`

There is also an issue with `package.json` of `jest-fail-on-console`. It doesn't specify `chalk` in `peerDependency` section, therefore required for project chalk version is neither validated during install nor installed.

--- 
**update**

Just found docs on chalk v5 breaking changes https://github.com/chalk/chalk/releases/tag/v5.0.0 and there are stated 

>It's totally fine to stay on Chalk v4. It's been stable for years.

So, just update to  `package.json` of `jest-fail-on-console` to include chalk@4 in  `peerDependency`  would be enough

**Comment by kopach** [comment]
sorry, my mistake, I had `chalk` mocked under `__mocks__` folder which caused all the issues for me

**Comment by ValentinH** [comment]
chalk V4 is declared as a dependency so it should be installed regardless of the version you are using.

**Comment by ValentinH** [comment]
I get the point. I have zero knowledge on this topic but I would be happy to review a PR removing chalk and hardcoding the tokens.

Would it work on windows as well?
